spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

spring.jackson.time-zone=America/Sao_Paulo

# Banco de produção
spring.datasource.url=${JDBC_DATASOURCE_URL}
spring.datasource.username=${JDBC_DATASOURCE_USERNAME}
spring.datasource.password=${JDBC_DATASOURCE_PASSWORD}


# CORS restrito (coloque o domínio do seu front React)
cors.allowed-origins=https://womenstales.com,https://app.womenstales.com